name: Build SoftEther VPN

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: centos:7
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yum groupinstall -y "Development Tools"
          yum install -y openssl-devel readline-devel zlib-devel

      - name: Compile SoftEther VPN
        run: |
          cd SoftEtherVPN
          ./configure
          make

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: softether-binaries
          path: SoftEtherVPN/bin
